#!/bin/bash
set -e

# ──────────────────────────────────────────────────────────────────────────────
# Kiro Bot Swarm (Docker) — Spawn N containers, each adding to ALL panels
#
# Usage:
#   ./spawn.sh                    # 1 container, all panels
#   ./spawn.sh --instances 3      # 3 containers, each adds to all panels
#   ./spawn.sh --dry-run          # Preview
#
# panels.json: each account is created once and added to ALL panels.
# More instances = more accounts created concurrently.
# ──────────────────────────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG="${SCRIPT_DIR}/panels.json"
DRY_RUN=false
INSTANCES=1

# Parse args
for i in "$@"; do
  case "$i" in
    --dry-run) DRY_RUN=true ;;
    --instances) shift_next=true ;;
    *) if [ "$shift_next" = "true" ]; then INSTANCES="$i"; shift_next=false; fi ;;
  esac
done
[ "$1" = "--dry-run" ] && DRY_RUN=true

if [ ! -f "$CONFIG" ]; then
  echo "ERROR: panels.json not found"
  exit 1
fi

# Generate compose file
python3 - "$CONFIG" "$INSTANCES" "$SCRIPT_DIR" <<'PYEOF'
import json, sys, os

config_path = sys.argv[1]
instances = int(sys.argv[2])
script_dir = sys.argv[3]

with open(config_path) as f:
    panels = json.load(f)

panel_urls = [p["url"] for p in panels]

services = []
for i in range(1, instances + 1):
    svc = f"""
  kiro-worker-{i}:
    build: .
    container_name: kiro-worker-{i}
    volumes:
      - ./output:/app/output
      - ./panels.json:/app/panels.json:ro
    environment:
      - PANELS=/app/panels.json
      - COUNT=99999
      - DOMAIN=fake.legal
      - COUNTRY=us
      - NO_PROXY=1
      - MAIL_PROVIDER=fake_legal
    restart: unless-stopped"""
    services.append(svc)

compose = f"""# Auto-generated by spawn.sh
# {instances} instance(s), each adds to {len(panels)} panel(s)
services:
{''.join(services)}
"""

compose_path = os.path.join(script_dir, "compose.swarm.yml")
with open(compose_path, "w") as f:
    f.write(compose)

print(f"Panels: {len(panels)}")
for p in panels:
    print(f"  - {p['url']}")
print(f"Instances: {instances}")
print(f"Each account → ALL panels")
print(f"Generated: {compose_path}")
PYEOF

echo ""

if [ "$DRY_RUN" = true ]; then
  echo "DRY RUN — not starting"
  exit 0
fi

echo "Starting swarm..."
cd "$SCRIPT_DIR"
docker compose -f compose.swarm.yml up -d --build
echo ""
echo "Logs:   docker compose -f compose.swarm.yml logs -f"
echo "Stop:   docker compose -f compose.swarm.yml down"
